# Feture engeniring

In [216]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
from wordcloud import WordCloud , STOPWORDS

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load both datasets from the data clansing

In [667]:
tv_ = pd.read_pickle("tv_show_3.pkl")
tv = pd.read_pickle("tv_show_cleaned.pkl")

tv_fit = pd.read_pickle("tv_for_features.pkl")

In [668]:
tv_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163047 entries, 0 to 168638
Data columns (total 26 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    163047 non-null  int64
 1   name                  163042 non-null  category
 2   number_of_seasons     163047 non-null  int64
 3   number_of_episodes    163047 non-null  int64
 4   original_language     163047 non-null  category
 5   vote_count            163047 non-null  int64
 6   vote_average          163047 non-null  float64
 7   overview              89749 non-null   string
 8   adult                 163047 non-null  bool
 9   in_production         163047 non-null  bool
 10  original_name         163042 non-null  category
 11  popularity            163047 non-null  float64
 12  type                  163047 non-null  category
 13  status                163047 non-null  category
 14  genres                96265 non-null   category
 15  languages             105931 non-null  category
 16  networks              95067 non-null   category
 17  origin_country        132404 non-null  category
 18  spoken_languages      105170 non-null  category
 19  production_countries  74937 non-null   category
 20  episode_run_time      163047 non-null  int64
 21  is_tagline            163047 non-null  int64
 22  year_start            131434 non-null  float64
 23  month_start           131450 non-null  float64
 24  year_end              133311 non-null  float64
 25  month_end             133311 non-null  float64
dtypes: bool(2), category(11), float64(6), int64(6), string(1)
memory usage: 22.7 MB

# Handle the name and origin name columns

In [669]:
#tv_['name'].head()
tv_['changed_name'] = tv_.apply(lambda x : 1 if x['name'] == x['original_name'] else 0, axis=1)
tv['changed_name'] = tv.apply(lambda x : 1 if x['name'] == x['original_name'] else 0, axis=1)
tv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163047 entries, 0 to 163046
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    163047 non-null  int64
 1   name                  163042 non-null  category
 2   number_of_seasons     163047 non-null  int64
 3   number_of_episodes    163047 non-null  int64
 4   original_language     163047 non-null  category
 5   vote_count            163047 non-null  int64
 6   vote_average          163047 non-null  float64
 7   overview              89749 non-null   string
 8   adult                 163047 non-null  bool
 9   in_production         163047 non-null  bool
 10  original_name         163042 non-null  category
 11  popularity            163047 non-null  float64
 12  type                  163047 non-null  category
 13  status                163047 non-null  category
 14  genres                163047 non-null  int64
 15  languages             163047 non-null  int64
 16  networks              163047 non-null  int64
 17  origin_country        163047 non-null  float64
 18  spoken_languages      163047 non-null  int64
 19  production_countries  163047 non-null  int64
 20  episode_run_time      163047 non-null  int64
 21  is_tagline            163047 non-null  int64
 22  year_start            163047 non-null  float64
 23  month_start           163047 non-null  float64
 24  year_end              163047 non-null  int64
 25  month_end             163047 non-null  float64
 26  changed_name          163047 non-null  int64
dtypes: bool(2), category(5), float64(6), int64(13), string(1)
memory usage: 29.2 MB

In [670]:
# If the same show name repeat
tv_['name_is_duplicate'] = tv_['name'].duplicated(keep=False).astype(int)
tv['name_is_duplicate'] = tv['name'].duplicated(keep=False).astype(int)
#tv_['name_is_duplicate'].head(25)

In [671]:
# Drop name and original name 
tv= tv.drop('original_name', axis=1)
tv_= tv_.drop('original_name', axis=1)
#tv_ = tv_.drop(['name','original_name'], axis=1)
tv_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163047 entries, 0 to 168638
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    163047 non-null  int64
 1   name                  163042 non-null  category
 2   number_of_seasons     163047 non-null  int64
 3   number_of_episodes    163047 non-null  int64
 4   original_language     163047 non-null  category
 5   vote_count            163047 non-null  int64
 6   vote_average          163047 non-null  float64
 7   overview              89749 non-null   string
 8   adult                 163047 non-null  bool
 9   in_production         163047 non-null  bool
 10  popularity            163047 non-null  float64
 11  type                  163047 non-null  category
 12  status                163047 non-null  category
 13  genres                96265 non-null   category
 14  languages             105931 non-null  category
 15  networks              95067 non-null   category
 16  origin_country        132404 non-null  category
 17  spoken_languages      105170 non-null  category
 18  production_countries  74937 non-null   category
 19  episode_run_time      163047 non-null  int64
 20  is_tagline            163047 non-null  int64
 21  year_start            131434 non-null  float64
 22  month_start           131450 non-null  float64
 23  year_end              133311 non-null  float64
 24  month_end             133311 non-null  float64
 25  changed_name          163047 non-null  int64
 26  name_is_duplicate     163047 non-null  int64
dtypes: bool(2), category(10), float64(6), int64(8), string(1)
memory usage: 23.4 MB

# Add a column that specifies if the value is zero for key columns

In [672]:
# zero value columns
cols_0 = ['vote_count','vote_average','number_of_seasons','number_of_episodes','episode_run_time']
for col in cols_0:
    tv[f'{col}_is_zero'] = tv[col].apply(lambda x: 1 if x==0 else 0)
    tv_[f'{col}_is_zero'] = tv_[col].apply(lambda x: 1 if x==0 else 0)

tv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163047 entries, 0 to 163046
Data columns (total 32 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   overview                    89749 non-null   string
 8   adult                       163047 non-null  bool
 9   in_production               163047 non-null  bool
 10  popularity                  163047 non-null  float64
 11  type                        163047 non-null  category
 12  status                      163047 non-null  category
 13  genres                      163047 non-null  int64
 14  languages                   163047 non-null  int64
 15  networks                    163047 non-null  int64
 16  origin_country              163047 non-null  float64
 17  spoken_languages            163047 non-null  int64
 18  production_countries        163047 non-null  int64
 19  episode_run_time            163047 non-null  int64
 20  is_tagline                  163047 non-null  int64
 21  year_start                  163047 non-null  float64
 22  month_start                 163047 non-null  float64
 23  year_end                    163047 non-null  int64
 24  month_end                   163047 non-null  float64
 25  changed_name                163047 non-null  int64
 26  name_is_duplicate           163047 non-null  int64
 27  vote_count_is_zero          163047 non-null  int64
 28  vote_average_is_zero        163047 non-null  int64
 29  number_of_seasons_is_zero   163047 non-null  int64
 30  number_of_episodes_is_zero  163047 non-null  int64
 31  episode_run_time_is_zero    163047 non-null  int64
dtypes: bool(2), category(4), float64(6), int64(19), string(1)
memory usage: 34.9 MB

# Start with handling the overview column

In [673]:
#tv_['overview'].info()
#tv_.info()
tv_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163047 entries, 0 to 168638
Data columns (total 32 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   overview                    89749 non-null   string
 8   adult                       163047 non-null  bool
 9   in_production               163047 non-null  bool
 10  popularity                  163047 non-null  float64
 11  type                        163047 non-null  category
 12  status                      163047 non-null  category
 13  genres                      96265 non-null   category
 14  languages                   105931 non-null  category
 15  networks                    95067 non-null   category
 16  origin_country              132404 non-null  category
 17  spoken_languages            105170 non-null  category
 18  production_countries        74937 non-null   category
 19  episode_run_time            163047 non-null  int64
 20  is_tagline                  163047 non-null  int64
 21  year_start                  131434 non-null  float64
 22  month_start                 131450 non-null  float64
 23  year_end                    133311 non-null  float64
 24  month_end                   133311 non-null  float64
 25  changed_name                163047 non-null  int64
 26  name_is_duplicate           163047 non-null  int64
 27  vote_count_is_zero          163047 non-null  int64
 28  vote_average_is_zero        163047 non-null  int64
 29  number_of_seasons_is_zero   163047 non-null  int64
 30  number_of_episodes_is_zero  163047 non-null  int64
 31  episode_run_time_is_zero    163047 non-null  int64
dtypes: bool(2), category(10), float64(6), int64(13), string(1)
memory usage: 29.6 MB

In [674]:
from textblob import TextBlob, Word, Blobber

def polarity(text):
    if not pd.isna(text):
        return TextBlob(text).sentiment.polarity
    else:
        return text
    
def subjectivity(text):
    if not pd.isna(text):
        return TextBlob(text).sentiment.subjectivity
    else:
        return text
    
    
tv_['polarity'] = tv_['overview'].apply(polarity)
tv_['subjectivity'] = tv_['overview'].apply(subjectivity)

tv['polarity'] = tv['overview'].apply(polarity)
tv['subjectivity'] = tv['overview'].apply(subjectivity)

In [363]:
tv_['polarity'].head(20)

0        -0.08
1    -0.046032
2    -0.231548
3     0.091667
4    -0.351111
5     0.144444
6        0.055
7     0.047273
8    -0.011111
9          0.0
10    0.078193
11    0.016667
12       0.075
13    0.016667
14         0.0
15       -0.06
16    0.231111
17         0.5
18         0.1
19         0.2
Name: polarity, dtype: object

In [ ]:
#tv_['subjectivity'].max()

1.0

In [675]:
tv_['sentiment'] = tv_['polarity'].apply(lambda x: np.nan if pd.isna(x) else 1 if x > 0 else -1 if x < 0 else 0)
tv['sentiment'] = tv['polarity'].apply(lambda x: np.nan if pd.isna(x) else 1 if x > 0 else -1 if x < 0 else 0)

tv['sentiment'].head()

0   -1.0
1   -1.0
2   -1.0
3    1.0
4   -1.0
Name: sentiment, dtype: float64

In [676]:
tv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163047 entries, 0 to 163046
Data columns (total 35 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   overview                    89749 non-null   string
 8   adult                       163047 non-null  bool
 9   in_production               163047 non-null  bool
 10  popularity                  163047 non-null  float64
 11  type                        163047 non-null  category
 12  status                      163047 non-null  category
 13  genres                      163047 non-null  int64
 14  languages                   163047 non-null  int64
 15  networks                    163047 non-null  int64
 16  origin_country              163047 non-null  float64
 17  spoken_languages            163047 non-null  int64
 18  production_countries        163047 non-null  int64
 19  episode_run_time            163047 non-null  int64
 20  is_tagline                  163047 non-null  int64
 21  year_start                  163047 non-null  float64
 22  month_start                 163047 non-null  float64
 23  year_end                    163047 non-null  int64
 24  month_end                   163047 non-null  float64
 25  changed_name                163047 non-null  int64
 26  name_is_duplicate           163047 non-null  int64
 27  vote_count_is_zero          163047 non-null  int64
 28  vote_average_is_zero        163047 non-null  int64
 29  number_of_seasons_is_zero   163047 non-null  int64
 30  number_of_episodes_is_zero  163047 non-null  int64
 31  episode_run_time_is_zero    163047 non-null  int64
 32  polarity                    89749 non-null   object
 33  subjectivity                89749 non-null   object
 34  sentiment                   89749 non-null   float64
dtypes: bool(2), category(4), float64(7), int64(19), object(2), string(1)
memory usage: 38.6+ MB

## Extract the top 10 most used words for the top 10 most popular shows after deducting the most frequent amongs the bottom 50% popularity values

In [677]:
from collections import Counter
top_popularity = tv_['overview'][tv_['popularity'] < tv_['popularity'].quantile(0.5)]
exlude = ['series', 'show', 'will','new']# 'two','television','aired','one','school','young','american','life','world','life']
# 1. Combine all overviews into a single string
text = " ".join(top_popularity.dropna().astype(str))

# 2. Optionally clean the text (lowercase, remove punctuation etc.)
text = text.lower()

# 3. Define stopwords to exclude common words
stopwords = set(STOPWORDS).union(set(exlude))

# 4. Split text into words and filter out stopwords
words = [word for word in text.split() if word not in stopwords  and word.isalpha()]

# 5. Count word frequencies
word_freq = Counter(words)

# 6. Get the top 10 most common words
tail_10_words = word_freq.most_common(15)

# 7. Convert to DataFrame for display
tail_words_df = pd.DataFrame(tail_10_words, columns=["word", "frequency"])

tail_15_words = tail_words_df['word'].values
tail_15_words = list(tail_15_words)

print(tail_15_words)

#print(top_words_df)

#top_popularity.head()

['television', 'aired', 'first', 'one', 'produced', 'broadcast', 'tv', 'program', 'hosted', 'two', 'world', 'life', 'story', 'news', 'american']

In [678]:
top_popularity = tv_['overview'][tv_['popularity'] > tv_['popularity'].quantile(0.85)]
exlude = ['series', 'show', 'will','new', 'two','television','aired','one','school','young']
exlude.extend(tail_15_words)
# 1. Combine all overviews into a single string
text = " ".join(top_popularity.dropna().astype(str))

# 2. Optionally clean the text (lowercase, remove punctuation etc.)
text = text.lower()

# 3. Define stopwords to exclude common words
stopwords = set(STOPWORDS).union(set(exlude))

# 4. Split text into words and filter out stopwords
words = [word for word in text.split() if word not in stopwords  and word.isalpha()]

# 5. Count word frequencies
word_freq = Counter(words)

# 6. Get the top 10 most common words
top_10_words = word_freq.most_common(15)

# 7. Convert to DataFrame for display
top_words_df = pd.DataFrame(top_10_words, columns=["word", "frequency"])
print(top_words_df)
top_15_words = top_words_df['word'].values

      word  frequency
0   family       1781
1     love       1659
2    drama       1277
3    lives       1232
4    years       1214
5    three       1195
6    based       1186
7     high       1130
8     find       1129
9     time       1100
10  around       1053
11  people       1046
12    best        982
13    girl        979
14     set        971

# Creat a new top words column

In [679]:
tv_['top_words'] = 0
tv['top_words'] = 0

######
tv_['top_words'] = tv_['overview'].apply(lambda x: np.nan if pd.isna(x) else 1 if any(word in x.lower().split() for word in top_15_words) else 0)
tv['top_words'] = tv['overview'].apply(lambda x: np.nan if pd.isna(x) else 1 if any(word in x.lower().split() for word in top_15_words) else 0)

#tv_['top_words'].head(30)
tv_.info()
tv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163047 entries, 0 to 168638
Data columns (total 36 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   overview                    89749 non-null   string
 8   adult                       163047 non-null  bool
 9   in_production               163047 non-null  bool
 10  popularity                  163047 non-null  float64
 11  type                        163047 non-null  category
 12  status                      163047 non-null  category
 13  genres                      96265 non-null   category
 14  languages                   105931 non-null  category
 15  networks                    95067 non-null   category
 16  origin_country              132404 non-null  category
 17  spoken_languages            105170 non-null  category
 18  production_countries        74937 non-null   category
 19  episode_run_time            163047 non-null  int64
 20  is_tagline                  163047 non-null  int64
 21  year_start                  131434 non-null  float64
 22  month_start                 131450 non-null  float64
 23  year_end                    133311 non-null  float64
 24  month_end                   133311 non-null  float64
 25  changed_name                163047 non-null  int64
 26  name_is_duplicate           163047 non-null  int64
 27  vote_count_is_zero          163047 non-null  int64
 28  vote_average_is_zero        163047 non-null  int64
 29  number_of_seasons_is_zero   163047 non-null  int64
 30  number_of_episodes_is_zero  163047 non-null  int64
 31  episode_run_time_is_zero    163047 non-null  int64
 32  polarity                    89749 non-null   object
 33  subjectivity                89749 non-null   object
 34  sentiment                   89749 non-null   float64
 35  top_words                   89749 non-null   float64
dtypes: bool(2), category(10), float64(8), int64(13), object(2), string(1)
memory usage: 34.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163047 entries, 0 to 163046
Data columns (total 36 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   overview                    89749 non-null   string
 8   adult                       163047 non-null  bool
 9   in_production               163047 non-null  bool
 10  popularity                  163047 non-null  float64
 11  type                        163047 non-null  category
 12  status                      163047 non-null  category
 13  genres                      163047 non-null  int64
 14  languages                   163047 non-null  int64
 15  networks                    163047 non-null  int64
 16  origin_country              163047 non-null  float64
 17  spoken_languages            163047 non-null  int64
 18  production_countries        163047 non-null  int64
 19  episode_run_time            163047 non-null  int64
 20  is_tagline                  163047 non-null  int64
 21  year_start                  163047 non-null  float64
 22  month_start                 163047 non-null  float64
 23  year_end                    163047 non-null  int64
 24  month_end                   163047 non-null  float64
 25  changed_name                163047 non-null  int64
 26  name_is_duplicate           163047 non-null  int64
 27  vote_count_is_zero          163047 non-null  int64
 28  vote_average_is_zero        163047 non-null  int64
 29  number_of_seasons_is_zero   163047 non-null  int64
 30  number_of_episodes_is_zero  163047 non-null  int64
 31  episode_run_time_is_zero    163047 non-null  int64
 32  polarity                    89749 non-null   object
 33  subjectivity                89749 non-null   object
 34  sentiment                   89749 non-null   float64
 35  top_words                   89749 non-null   float64
dtypes: bool(2), category(4), float64(8), int64(19), object(2), string(1)
memory usage: 39.9+ MB

## Lengh of overview column

In [680]:
def word_len(row):
    if pd.isna(row):  # Handle NaN values
        return 0 # instead of nan returns 0
    return len(row.split(' '))  # Count words
    
tv_['overview_length'] = tv_['overview'].apply(word_len)
tv['overview_length'] = tv['overview'].apply(word_len)

tv_.info()
tv.info()
#print(tv_['overview_length'].isnull().sum()) # = 0
#print(tv_['popularity'].isnull().sum()) # = 0



#tv_cop = tv_.loc[tv_['overview_length'] !=-0]
# Scatter plot (corrected)
#sns.scatterplot(data=tv_cop, x='overview_length', y='popularity')
#plt.show()
#sns.scatterplot(data=tv_, x='overview_length', y='popularity')
#plt.show()

<class 'pandas.core.frame.DataFrame'>
Index: 163047 entries, 0 to 168638
Data columns (total 37 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   overview                    89749 non-null   string
 8   adult                       163047 non-null  bool
 9   in_production               163047 non-null  bool
 10  popularity                  163047 non-null  float64
 11  type                        163047 non-null  category
 12  status                      163047 non-null  category
 13  genres                      96265 non-null   category
 14  languages                   105931 non-null  category
 15  networks                    95067 non-null   category
 16  origin_country              132404 non-null  category
 17  spoken_languages            105170 non-null  category
 18  production_countries        74937 non-null   category
 19  episode_run_time            163047 non-null  int64
 20  is_tagline                  163047 non-null  int64
 21  year_start                  131434 non-null  float64
 22  month_start                 131450 non-null  float64
 23  year_end                    133311 non-null  float64
 24  month_end                   133311 non-null  float64
 25  changed_name                163047 non-null  int64
 26  name_is_duplicate           163047 non-null  int64
 27  vote_count_is_zero          163047 non-null  int64
 28  vote_average_is_zero        163047 non-null  int64
 29  number_of_seasons_is_zero   163047 non-null  int64
 30  number_of_episodes_is_zero  163047 non-null  int64
 31  episode_run_time_is_zero    163047 non-null  int64
 32  polarity                    89749 non-null   object
 33  subjectivity                89749 non-null   object
 34  sentiment                   89749 non-null   float64
 35  top_words                   89749 non-null   float64
 36  overview_length             163047 non-null  int64
dtypes: bool(2), category(10), float64(8), int64(14), object(2), string(1)
memory usage: 35.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163047 entries, 0 to 163046
Data columns (total 37 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   overview                    89749 non-null   string
 8   adult                       163047 non-null  bool
 9   in_production               163047 non-null  bool
 10  popularity                  163047 non-null  float64
 11  type                        163047 non-null  category
 12  status                      163047 non-null  category
 13  genres                      163047 non-null  int64
 14  languages                   163047 non-null  int64
 15  networks                    163047 non-null  int64
 16  origin_country              163047 non-null  float64
 17  spoken_languages            163047 non-null  int64
 18  production_countries        163047 non-null  int64
 19  episode_run_time            163047 non-null  int64
 20  is_tagline                  163047 non-null  int64
 21  year_start                  163047 non-null  float64
 22  month_start                 163047 non-null  float64
 23  year_end                    163047 non-null  int64
 24  month_end                   163047 non-null  float64
 25  changed_name                163047 non-null  int64
 26  name_is_duplicate           163047 non-null  int64
 27  vote_count_is_zero          163047 non-null  int64
 28  vote_average_is_zero        163047 non-null  int64
 29  number_of_seasons_is_zero   163047 non-null  int64
 30  number_of_episodes_is_zero  163047 non-null  int64
 31  episode_run_time_is_zero    163047 non-null  int64
 32  polarity                    89749 non-null   object
 33  subjectivity                89749 non-null   object
 34  sentiment                   89749 non-null   float64
 35  top_words                   89749 non-null   float64
 36  overview_length             163047 non-null  int64
dtypes: bool(2), category(4), float64(8), int64(20), object(2), string(1)
memory usage: 41.1+ MB

In [681]:
# Drop overview:
tv = tv.drop('overview', axis=1)
tv_ = tv_.drop('overview', axis=1)
tv_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163047 entries, 0 to 168638
Data columns (total 36 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   adult                       163047 non-null  bool
 8   in_production               163047 non-null  bool
 9   popularity                  163047 non-null  float64
 10  type                        163047 non-null  category
 11  status                      163047 non-null  category
 12  genres                      96265 non-null   category
 13  languages                   105931 non-null  category
 14  networks                    95067 non-null   category
 15  origin_country              132404 non-null  category
 16  spoken_languages            105170 non-null  category
 17  production_countries        74937 non-null   category
 18  episode_run_time            163047 non-null  int64
 19  is_tagline                  163047 non-null  int64
 20  year_start                  131434 non-null  float64
 21  month_start                 131450 non-null  float64
 22  year_end                    133311 non-null  float64
 23  month_end                   133311 non-null  float64
 24  changed_name                163047 non-null  int64
 25  name_is_duplicate           163047 non-null  int64
 26  vote_count_is_zero          163047 non-null  int64
 27  vote_average_is_zero        163047 non-null  int64
 28  number_of_seasons_is_zero   163047 non-null  int64
 29  number_of_episodes_is_zero  163047 non-null  int64
 30  episode_run_time_is_zero    163047 non-null  int64
 31  polarity                    89749 non-null   object
 32  subjectivity                89749 non-null   object
 33  sentiment                   89749 non-null   float64
 34  top_words                   89749 non-null   float64
 35  overview_length             163047 non-null  int64
dtypes: bool(2), category(10), float64(8), int64(14), object(2)
memory usage: 34.6+ MB

# Adding columns for the number of spoken langauge, production_countries ...
this is the original data on which I added those new columns before doing the column grouping and cleaning.
I counted the number of instances per specific column such as spoken language, production countries for example: the number of production countries in producing the show 
if for example there are multiple production countries in a show this could imply that the show has high budget and a high budget show coul imply for a popular show.

In [682]:
#this is the original data on which i added those new columns before doing the column grouping and cleaning

#tv_fit.info()
columns = [col for col in tv_fit.columns if col.endswith('_num')]
print(columns) 
for col in columns:
    tv_[col] = tv_fit[col]
    tv[col] = tv_fit[col]   

#tv_.info()
tv.info()

['languages_num', 'spoken_languages_num', 'production_countries_num', 'networks_num']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163047 entries, 0 to 163046
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   adult                       163047 non-null  bool
 8   in_production               163047 non-null  bool
 9   popularity                  163047 non-null  float64
 10  type                        163047 non-null  category
 11  status                      163047 non-null  category
 12  genres                      163047 non-null  int64
 13  languages                   163047 non-null  int64
 14  networks                    163047 non-null  int64
 15  origin_country              163047 non-null  float64
 16  spoken_languages            163047 non-null  int64
 17  production_countries        163047 non-null  int64
 18  episode_run_time            163047 non-null  int64
 19  is_tagline                  163047 non-null  int64
 20  year_start                  163047 non-null  float64
 21  month_start                 163047 non-null  float64
 22  year_end                    163047 non-null  int64
 23  month_end                   163047 non-null  float64
 24  changed_name                163047 non-null  int64
 25  name_is_duplicate           163047 non-null  int64
 26  vote_count_is_zero          163047 non-null  int64
 27  vote_average_is_zero        163047 non-null  int64
 28  number_of_seasons_is_zero   163047 non-null  int64
 29  number_of_episodes_is_zero  163047 non-null  int64
 30  episode_run_time_is_zero    163047 non-null  int64
 31  polarity                    89749 non-null   object
 32  subjectivity                89749 non-null   object
 33  sentiment                   89749 non-null   float64
 34  top_words                   89749 non-null   float64
 35  overview_length             163047 non-null  int64
 36  languages_num               107158 non-null  float64
 37  spoken_languages_num        106415 non-null  float64
 38  production_countries_num    75518 non-null   float64
 39  networks_num                95122 non-null   float64
dtypes: bool(2), category(4), float64(12), int64(20), object(2)
memory usage: 44.8+ MB

In [683]:
tv.head(10)

,id,name,number_of_seasons,number_of_episodes,original_language,vote_count,vote_average,adult,in_production,popularity,type,status,genres,languages,networks,origin_country,spoken_languages,production_countries,episode_run_time,is_tagline,year_start,month_start,year_end,month_end,changed_name,name_is_duplicate,vote_count_is_zero,vote_average_is_zero,number_of_seasons_is_zero,number_of_episodes_is_zero,episode_run_time_is_zero,polarity,subjectivity,sentiment,top_words,overview_length,languages_num,spoken_languages_num,production_countries_num,networks_num
0,1399,Game of Thrones,8,73,en,21857,8.442,False,False,1083.917,Scripted,Ended,13,6,12,19.0,2,23,0,1,2011.0,4.0,2019,5.0,1,0,0,0,0,0,1,-0.08,0.48,-1.0,0.0,56,1.0,1.0,2.0,1.0
1,71446,Money Heist,3,41,es,17836,8.257,False,False,96.354,Scripted,Ended,5,7,21,6.0,3,17,70,1,2017.0,5.0,2021,12.0,0,0,0,0,0,0,0,-0.046032,0.560317,-1.0,1.0,85,1.0,1.0,1.0,2.0
2,66732,Stranger Things,4,34,en,16161,8.624,False,True,185.711,Scripted,Returning Series,13,6,11,19.0,2,22,0,1,2016.0,7.0,2022,7.0,1,0,0,0,0,0,1,-0.231548,0.530952,-1.0,0.0,22,1.0,1.0,1.0,1.0
3,1402,The Walking Dead,11,177,en,15432,8.121,False,False,489.746,Scripted,Ended,13,6,12,19.0,2,22,42,1,2010.0,10.0,2022,11.0,1,0,0,0,0,0,0,0.091667,0.291667,1.0,1.0,32,1.0,1.0,1.0,1.0
4,63174,Lucifer,6,93,en,13870,8.486,False,False,416.668,Scripted,Ended,13,6,21,19.0,2,22,45,1,2016.0,1.0,2021,9.0,1,0,0,0,0,0,0,-0.351111,0.737778,-1.0,0.0,50,1.0,1.0,1.0,2.0
5,69050,Riverdale,7,137,en,13180,8.479,False,False,143.750,Scripted,Ended,13,6,12,19.0,2,22,45,1,2017.0,1.0,2023,8.0,1,1,0,0,0,0,0,0.144444,0.222222,1.0,1.0,33,1.0,1.0,1.0,1.0
6,93405,Squid Game,2,9,ko,13053,7.831,False,True,115.587,Scripted,Returning Series,13,13,11,13.0,12,16,0,1,2021.0,9.0,2021,9.0,0,0,0,0,0,0,1,0.055,0.345,1.0,1.0,22,3.0,3.0,1.0,1.0
7,1396,Breaking Bad,5,62,en,12398,8.890,False,False,247.632,Scripted,Ended,5,13,12,19.0,12,22,0,1,2008.0,1.0,2013,9.0,1,0,0,0,0,0,1,0.047273,0.447955,1.0,1.0,56,3.0,3.0,1.0,1.0
8,71712,The Good Doctor,6,116,en,11768,8.503,False,True,681.614,Scripted,Returning Series,7,6,0,19.0,2,22,43,1,2017.0,9.0,2023,5.0,1,0,0,0,0,0,0,-0.011111,0.422222,-1.0,1.0,47,1.0,1.0,1.0,1.0
9,85271,WandaVision,1,9,en,11308,8.300,False,False,62.893,Miniseries,Ended,13,6,12,19.0,2,22,0,1,2021.0,1.0,2021,3.0,1,0,0,0,0,0,1,0.0,0.0,0.0,0.0,19,1.0,1.0,1.0,1.0

# Air time column
The duration in which the show been played

In [684]:
tv_.head(20)
#Adding column for period of each show and removing the date time 


def aired_t(row):
    if pd.isna(row['year_start']) or pd.isna(row['year_end']) or \
           pd.isna(row['month_start']) or pd.isna(row['month_end']):
            return pd.NA  # Keep NaN values
    
    aired = (row['year_end'] - row['year_start']) * 12 + (row['month_end'] - row['month_start'])
    return aired / 12.0

tv_['aired_time'] =tv_.apply(aired_t, axis=1)
tv['aired_time'] =tv.apply(aired_t, axis=1)
tv_['aired_time'] = pd.to_numeric(tv_['aired_time'], errors='coerce').astype('float64')
tv['aired_time'] = pd.to_numeric(tv['aired_time'], errors='coerce').astype('float64')
#tv_['aired_time'] = (tv_['last_air_year'] - tv_['first_air_year']) *12 + (tv_['last_air_month'] - tv_['first_air_month'])
#tv_['aired_time']=tv_['aired_time']/12

tv_['aired_time'].head()

0     8.083333
1     4.583333
2     6.000000
3    12.083333
4     5.666667
Name: aired_time, dtype: float64

## Average episodes per season

In [685]:
# Average episode per season 
tv_['avg_episodes_per_season'] = (tv_['number_of_episodes'] / tv_['number_of_seasons']).where(tv_['number_of_seasons'] > 0, 0)

tv['avg_episodes_per_season'] = (tv['number_of_episodes'] / tv['number_of_seasons']).where(tv['number_of_seasons'] > 0, 0)

tv_['avg_episodes_per_season'].head(30)

0      9.125000
1     13.666667
2      8.500000
3     16.090909
4     15.500000
5     19.571429
6      4.500000
7     12.400000
8     19.333333
9      9.000000
10    20.444444
11    23.250000
12     6.000000
13    22.052632
14     8.000000
15    21.771429
16     8.000000
17     8.000000
18     6.000000
19     7.000000
20     8.000000
21    10.142857
22    21.375000
23     6.000000
24    25.000000
25    14.285714
26     4.000000
27    22.800000
28    21.800000
29     8.000000
Name: avg_episodes_per_season, dtype: float64

In [686]:
tv_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163047 entries, 0 to 168638
Data columns (total 42 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   adult                       163047 non-null  bool
 8   in_production               163047 non-null  bool
 9   popularity                  163047 non-null  float64
 10  type                        163047 non-null  category
 11  status                      163047 non-null  category
 12  genres                      96265 non-null   category
 13  languages                   105931 non-null  category
 14  networks                    95067 non-null   category
 15  origin_country              132404 non-null  category
 16  spoken_languages            105170 non-null  category
 17  production_countries        74937 non-null   category
 18  episode_run_time            163047 non-null  int64
 19  is_tagline                  163047 non-null  int64
 20  year_start                  131434 non-null  float64
 21  month_start                 131450 non-null  float64
 22  year_end                    133311 non-null  float64
 23  month_end                   133311 non-null  float64
 24  changed_name                163047 non-null  int64
 25  name_is_duplicate           163047 non-null  int64
 26  vote_count_is_zero          163047 non-null  int64
 27  vote_average_is_zero        163047 non-null  int64
 28  number_of_seasons_is_zero   163047 non-null  int64
 29  number_of_episodes_is_zero  163047 non-null  int64
 30  episode_run_time_is_zero    163047 non-null  int64
 31  polarity                    89749 non-null   object
 32  subjectivity                89749 non-null   object
 33  sentiment                   89749 non-null   float64
 34  top_words                   89749 non-null   float64
 35  overview_length             163047 non-null  int64
 36  languages_num               105931 non-null  float64
 37  spoken_languages_num        105170 non-null  float64
 38  production_countries_num    74937 non-null   float64
 39  networks_num                95067 non-null   float64
 40  aired_time                  130439 non-null  float64
 41  avg_episodes_per_season     163047 non-null  float64
dtypes: bool(2), category(10), float64(14), int64(14), object(2)
memory usage: 42.0+ MB

# Add a column for the annual growth rate of people access to tv
There are a segnificant change in the people access to TV shows (streaming services raised this accesability) among the years of the shows in the DATA
therfore , I added a growth index
The index value of the erliest year is 100

In [ ]:

#print(tv['year_start'].min())

1970.0

In [688]:
tv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163047 entries, 0 to 163046
Data columns (total 42 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   adult                       163047 non-null  bool
 8   in_production               163047 non-null  bool
 9   popularity                  163047 non-null  float64
 10  type                        163047 non-null  category
 11  status                      163047 non-null  category
 12  genres                      163047 non-null  int64
 13  languages                   163047 non-null  int64
 14  networks                    163047 non-null  int64
 15  origin_country              163047 non-null  float64
 16  spoken_languages            163047 non-null  int64
 17  production_countries        163047 non-null  int64
 18  episode_run_time            163047 non-null  int64
 19  is_tagline                  163047 non-null  int64
 20  year_start                  163047 non-null  float64
 21  month_start                 163047 non-null  float64
 22  year_end                    163047 non-null  int64
 23  month_end                   163047 non-null  float64
 24  changed_name                163047 non-null  int64
 25  name_is_duplicate           163047 non-null  int64
 26  vote_count_is_zero          163047 non-null  int64
 27  vote_average_is_zero        163047 non-null  int64
 28  number_of_seasons_is_zero   163047 non-null  int64
 29  number_of_episodes_is_zero  163047 non-null  int64
 30  episode_run_time_is_zero    163047 non-null  int64
 31  polarity                    89749 non-null   object
 32  subjectivity                89749 non-null   object
 33  sentiment                   89749 non-null   float64
 34  top_words                   89749 non-null   float64
 35  overview_length             163047 non-null  int64
 36  languages_num               107158 non-null  float64
 37  spoken_languages_num        106415 non-null  float64
 38  production_countries_num    75518 non-null   float64
 39  networks_num                95122 non-null   float64
 40  aired_time                  163047 non-null  float64
 41  avg_episodes_per_season     163047 non-null  float64
dtypes: bool(2), category(4), float64(14), int64(20), object(2)
memory usage: 47.3+ MB

In [689]:
tv_['year_start'].min()

np.float64(1970.0)

In [690]:
max =tv['year_start'].max()
min = tv['year_start'].min() #1970
average_annual_growth_rate = 1.0216 # 2.16% - average growth rate
def ann_growth_rate(row):
    if row <=min:
        return 100
    years = row -min
    if years == 0:
        return 100
    else:
        return 100*average_annual_growth_rate**years
    
tv['growth_index'] = tv['year_start'].apply(ann_growth_rate)
tv_['growth_index'] = tv_['year_start'].apply(ann_growth_rate)

## If top network

In [691]:
top_net_lst=['CBS','FOX','NBC','Netflix','multiple_top_20']
for net in top_net_lst:
    tv_[f'is{net}'] = tv_['networks'].apply(lambda x: 1 if x == net else -1 if pd.isna(x) else 0 )
    tv[f'is{net}'] = tv_['networks'].apply(lambda x: 1 if x == net else -1 if pd.isna(x) else 0 )

In [692]:
tv.info(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163047 entries, 0 to 163046
Data columns (total 48 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   adult                       163047 non-null  bool
 8   in_production               163047 non-null  bool
 9   popularity                  163047 non-null  float64
 10  type                        163047 non-null  category
 11  status                      163047 non-null  category
 12  genres                      163047 non-null  int64
 13  languages                   163047 non-null  int64
 14  networks                    163047 non-null  int64
 15  origin_country              163047 non-null  float64
 16  spoken_languages            163047 non-null  int64
 17  production_countries        163047 non-null  int64
 18  episode_run_time            163047 non-null  int64
 19  is_tagline                  163047 non-null  int64
 20  year_start                  163047 non-null  float64
 21  month_start                 163047 non-null  float64
 22  year_end                    163047 non-null  int64
 23  month_end                   163047 non-null  float64
 24  changed_name                163047 non-null  int64
 25  name_is_duplicate           163047 non-null  int64
 26  vote_count_is_zero          163047 non-null  int64
 27  vote_average_is_zero        163047 non-null  int64
 28  number_of_seasons_is_zero   163047 non-null  int64
 29  number_of_episodes_is_zero  163047 non-null  int64
 30  episode_run_time_is_zero    163047 non-null  int64
 31  polarity                    89749 non-null   object
 32  subjectivity                89749 non-null   object
 33  sentiment                   89749 non-null   float64
 34  top_words                   89749 non-null   float64
 35  overview_length             163047 non-null  int64
 36  languages_num               107158 non-null  float64
 37  spoken_languages_num        106415 non-null  float64
 38  production_countries_num    75518 non-null   float64
 39  networks_num                95122 non-null   float64
 40  aired_time                  163047 non-null  float64
 41  avg_episodes_per_season     163047 non-null  float64
 42  growth_index                163047 non-null  float64
 43  isCBS                       92647 non-null   float64
 44  isFOX                       92647 non-null   float64
 45  isNBC                       92647 non-null   float64
 46  isNetflix                   92647 non-null   float64
 47  ismultiple_top_20           92647 non-null   float64
dtypes: bool(2), category(4), float64(20), int64(20), object(2)
memory usage: 54.8+ MB

In [660]:
# columns with NAN on the not cleaned data
cols_with_nans = tv_.columns[tv_.isnull().any()].tolist()
print(cols_with_nans)
print(tv_[cols_with_nans].dtypes)

['name', 'number_of_seasons', 'genres', 'languages', 'networks', 'origin_country', 'spoken_languages', 'production_countries', 'episode_run_time', 'year_start', 'month_start', 'year_end', 'month_end', 'polarity', 'subjectivity', 'sentiment', 'top_words', 'languages_num', 'spoken_languages_num', 'production_countries_num', 'networks_num', 'aired_time', 'growth_index', 'isCBS', 'isFOX', 'isNBC', 'isNetflix', 'ismultiple_top_20']
name                        category
number_of_seasons            float64
genres                      category
languages                   category
networks                    category
origin_country              category
spoken_languages            category
production_countries        category
episode_run_time             float64
year_start                   float64
month_start                  float64
year_end                     float64
month_end                    float64
polarity                      object
subjectivity                  object
sentiment                    float64
top_words                    float64
languages_num                float64
spoken_languages_num         float64
production_countries_num     float64
networks_num                 float64
aired_time                   float64
growth_index                 float64
isCBS                        float64
isFOX                        float64
isNBC                        float64
isNetflix                    float64
ismultiple_top_20            float64
dtype: object

In [693]:
tv_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163047 entries, 0 to 168638
Data columns (total 48 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163042 non-null  category
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  category
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   adult                       163047 non-null  bool
 8   in_production               163047 non-null  bool
 9   popularity                  163047 non-null  float64
 10  type                        163047 non-null  category
 11  status                      163047 non-null  category
 12  genres                      96265 non-null   category
 13  languages                   105931 non-null  category
 14  networks                    95067 non-null   category
 15  origin_country              132404 non-null  category
 16  spoken_languages            105170 non-null  category
 17  production_countries        74937 non-null   category
 18  episode_run_time            163047 non-null  int64
 19  is_tagline                  163047 non-null  int64
 20  year_start                  131434 non-null  float64
 21  month_start                 131450 non-null  float64
 22  year_end                    133311 non-null  float64
 23  month_end                   133311 non-null  float64
 24  changed_name                163047 non-null  int64
 25  name_is_duplicate           163047 non-null  int64
 26  vote_count_is_zero          163047 non-null  int64
 27  vote_average_is_zero        163047 non-null  int64
 28  number_of_seasons_is_zero   163047 non-null  int64
 29  number_of_episodes_is_zero  163047 non-null  int64
 30  episode_run_time_is_zero    163047 non-null  int64
 31  polarity                    89749 non-null   object
 32  subjectivity                89749 non-null   object
 33  sentiment                   89749 non-null   float64
 34  top_words                   89749 non-null   float64
 35  overview_length             163047 non-null  int64
 36  languages_num               105931 non-null  float64
 37  spoken_languages_num        105170 non-null  float64
 38  production_countries_num    74937 non-null   float64
 39  networks_num                95067 non-null   float64
 40  aired_time                  130439 non-null  float64
 41  avg_episodes_per_season     163047 non-null  float64
 42  growth_index                131434 non-null  float64
 43  isCBS                       95067 non-null   float64
 44  isFOX                       95067 non-null   float64
 45  isNBC                       95067 non-null   float64
 46  isNetflix                   95067 non-null   float64
 47  ismultiple_top_20           95067 non-null   float64
dtypes: bool(2), category(10), float64(20), int64(14), object(2)
memory usage: 53.5+ MB

# One hot encoding

In [694]:
from sklearn.preprocessing import LabelEncoder

# for float cols i aded that has nulls :
#float_cols = tv.select_dtypes(include= [float,int]).columns
#tv_[float_cols] = tv_[float_cols].fillna(-1)
#tv[float_cols] = tv[float_cols].fillna(-1)

encoder = LabelEncoder()
for col in tv_.select_dtypes(include= ['object','string','category','bool']):
    tv_[col] = tv_[col].astype(str).fillna('missing')
    tv_[col] = encoder.fit_transform(tv_[col])
    
for col in tv.select_dtypes(include= ['object','string','category','bool']):  
    tv[col] = tv[col].astype(str).fillna('missing')
    tv[col] = encoder.fit_transform(tv[col])

for col in tv.select_dtypes(include= [ float, int]):
    tv[col] = tv[col].fillna(0)

for col in tv_.select_dtypes(include= [ float, int]):
    tv_[col] = tv_[col].fillna(0)

In [695]:


#tv.info()
#pd.set_option('display.max_columns', None)
# To see all of the columns
pd.DataFrame({'Column': tv.columns, 'Dtype': tv.dtypes.values})

                        Column    Dtype
0                           id    int64
1                         name    int64
2            number_of_seasons    int64
3           number_of_episodes    int64
4            original_language    int64
5                   vote_count    int64
6                 vote_average  float64
7                        adult    int64
8                in_production    int64
9                   popularity  float64
10                        type    int64
11                      status    int64
12                      genres    int64
13                   languages    int64
14                    networks    int64
15              origin_country  float64
16            spoken_languages    int64
17        production_countries    int64
18            episode_run_time    int64
19                  is_tagline    int64
20                  year_start  float64
21                 month_start  float64
22                    year_end    int64
23                   month_end  float64
24                changed_name    int64
25           name_is_duplicate    int64
26          vote_count_is_zero    int64
27        vote_average_is_zero    int64
28   number_of_seasons_is_zero    int64
29  number_of_episodes_is_zero    int64
30    episode_run_time_is_zero    int64
31                    polarity    int64
32                subjectivity    int64
33                   sentiment  float64
34                   top_words  float64
35             overview_length    int64
36               languages_num  float64
37        spoken_languages_num  float64
38    production_countries_num  float64
39                networks_num  float64
40                  aired_time  float64
41     avg_episodes_per_season  float64
42                growth_index  float64
43                       isCBS  float64
44                       isFOX  float64
45                       isNBC  float64
46                   isNetflix  float64
47           ismultiple_top_20  float64

# If the show played during corona time

In [696]:
tv['is_covid_time'] = tv['year_end'].apply(lambda x: 1 if x > 2022.0  else 0)
tv_['is_covid_time'] = tv_['year_end'].apply(lambda x: 1 if x > 2022.0  else 0)

In [ ]:
#Drop name 
#tv = tv.drop('name',axis=1)
#tv_ = tv_.drop('name',axis=1)

In [697]:
x_ = tv_.drop('popularity', axis=1)
y_ = tv_['popularity']

x = tv.drop('popularity', axis=1)
y = tv['popularity']

x.info()
#x_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163047 entries, 0 to 163046
Data columns (total 48 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id                          163047 non-null  int64
 1   name                        163047 non-null  int64
 2   number_of_seasons           163047 non-null  int64
 3   number_of_episodes          163047 non-null  int64
 4   original_language           163047 non-null  int64
 5   vote_count                  163047 non-null  int64
 6   vote_average                163047 non-null  float64
 7   adult                       163047 non-null  int64
 8   in_production               163047 non-null  int64
 9   type                        163047 non-null  int64
 10  status                      163047 non-null  int64
 11  genres                      163047 non-null  int64
 12  languages                   163047 non-null  int64
 13  networks                    163047 non-null  int64
 14  origin_country              163047 non-null  float64
 15  spoken_languages            163047 non-null  int64
 16  production_countries        163047 non-null  int64
 17  episode_run_time            163047 non-null  int64
 18  is_tagline                  163047 non-null  int64
 19  year_start                  163047 non-null  float64
 20  month_start                 163047 non-null  float64
 21  year_end                    163047 non-null  int64
 22  month_end                   163047 non-null  float64
 23  changed_name                163047 non-null  int64
 24  name_is_duplicate           163047 non-null  int64
 25  vote_count_is_zero          163047 non-null  int64
 26  vote_average_is_zero        163047 non-null  int64
 27  number_of_seasons_is_zero   163047 non-null  int64
 28  number_of_episodes_is_zero  163047 non-null  int64
 29  episode_run_time_is_zero    163047 non-null  int64
 30  polarity                    163047 non-null  int64
 31  subjectivity                163047 non-null  int64
 32  sentiment                   163047 non-null  float64
 33  top_words                   163047 non-null  float64
 34  overview_length             163047 non-null  int64
 35  languages_num               163047 non-null  float64
 36  spoken_languages_num        163047 non-null  float64
 37  production_countries_num    163047 non-null  float64
 38  networks_num                163047 non-null  float64
 39  aired_time                  163047 non-null  float64
 40  avg_episodes_per_season     163047 non-null  float64
 41  growth_index                163047 non-null  float64
 42  isCBS                       163047 non-null  float64
 43  isFOX                       163047 non-null  float64
 44  isNBC                       163047 non-null  float64
 45  isNetflix                   163047 non-null  float64
 46  ismultiple_top_20           163047 non-null  float64
 47  is_covid_time               163047 non-null  int64
dtypes: float64(19), int64(29)
memory usage: 59.7 MB

In [210]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import Lasso, Ridge
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

Display max columns, making sure again I have no NAN in the data.

In [633]:
pd.set_option('display.max_columns', None)
x.head()
print(x.isnull().sum())

id                            0
name                          0
number_of_seasons             0
number_of_episodes            0
original_language             0
vote_count                    0
vote_average                  0
adult                         0
in_production                 0
type                          0
status                        0
genres                        0
languages                     0
networks                      0
origin_country                0
spoken_languages              0
production_countries          0
episode_run_time              0
is_tagline                    0
year_start                    0
month_start                   0
year_end                      0
month_end                     0
changed_name                  0
name_is_duplicate             0
vote_count_is_zero            0
vote_average_is_zero          0
number_of_seasons_is_zero     0
number_of_episodes_is_zero    0
episode_run_time_is_zero      0
polarity                      0
subjectivity                  0
sentiment                     0
top_words                     0
overview_length               0
languages_num                 0
spoken_languages_num          0
production_countries_num      0
networks_num                  0
aired_time                    0
avg_episodes_per_season       0
growth_index                  0
isCBS                         0
isFOX                         0
isNBC                         0
isNetflix                     0
ismultiple_top_20             0
is_covid_time                 0
dtype: int64

In [421]:
# Check for infinite values in the DataFrame
inf_mask = np.isinf(x)

# Get column-wise summary
inf_summary = pd.DataFrame(inf_mask, columns=x.columns).any()

# Print only the columns with at least one inf/-inf
print("Columns with infinite values:")
print(inf_summary[inf_summary])

Columns with infinite values:
Series([], dtype: bool)

# I will use Gridsearch to find the best alpha for lasso and ridge model

In [136]:
# define alpha search space
alpha = {'alpha': np.logspace(-3, 2, 20)}
#LASSO
lasso_search = GridSearchCV(Lasso(max_iter=10000), alpha, cv=5)
lasso_search.fit(x, y)
best_lasso = lasso_search.best_estimator_
print("Best alpha for Lasso:", lasso_search.best_params_)

# Grid Search for Ridge
ridge_search = GridSearchCV(Ridge(), alpha, cv=5)
ridge_search.fit(x, y)

best_ridge = ridge_search.best_estimator_
print("Best alpha for Ridge:", ridge_search.best_params_)

Best alpha for Lasso: {'alpha': np.float64(54.555947811685144)}
Best alpha for Ridge: {'alpha': np.float64(100.0)}

The best found parameters are  lasso :54.44 , ridge : 100.
this alpha (especially for lasso ) yields very few columns left therfore i will reduce the lasso alpha until I have sufficient amount of columns.
alpa =1 found to be the best in term of total prediction score

In [ ]:
lasso = Lasso(alpha=1).fit(x, y)
lasso_selected = (np.abs(lasso.coef_) > 0).astype(int)

#Ridge
ridge = Ridge(alpha=100).fit(x, y)
ridge_selected = (np.abs(ridge.coef_) > 0).astype(int)

#Gradient Boosting
gb = GradientBoostingRegressor().fit(x, y)
gb_selected = (gb.feature_importances_ > 0).astype(int)

#Random Forest
rf = RandomForestRegressor().fit(x, y)
rf_selected = (rf.feature_importances_ > 0).astype(int)

# Create a DataFrame with the selected features
selected_features = pd.DataFrame({
    'Feature': x.columns,
    'Lasso': lasso_selected,
    'Ridge': ridge_selected,
    'GB': gb_selected,
    'RF': rf_selected
})

# Sum the totals for each model
selected_features['Total'] = selected_features[['Lasso','Ridge','GB','RF']].sum(axis=1)
print(selected_features)

                       Feature  Lasso  Ridge  GB  RF  Total
0                           id      1      1   1   1      4
1                         name      1      1   1   1      4
2            number_of_seasons      1      1   1   1      4
3           number_of_episodes      1      1   1   1      4
4            original_language      1      1   1   1      4
5                   vote_count      1      1   1   1      4
6                 vote_average      1      1   1   1      4
7                        adult      0      1   0   1      2
8                in_production      0      1   0   1      2
9                         type      1      1   1   1      4
10                      status      0      1   0   1      2
11                      genres      1      1   1   1      4
12                   languages      0      1   1   1      3
13                    networks      0      1   1   1      3
14              origin_country      0      1   0   1      2
15            spoken_languages      1      1   1   1      4
16        production_countries      1      1   1   1      4
17            episode_run_time      0      1   1   1      3
18                  is_tagline      0      1   1   1      3
19                  year_start      1      1   1   1      4
20                 month_start      0      1   1   1      3
21                    year_end      0      1   1   1      3
22                   month_end      1      1   1   1      4
23                changed_name      0      1   1   1      3
24           name_is_duplicate      0      1   0   1      2
25          vote_count_is_zero      0      1   0   1      2
26        vote_average_is_zero      0      1   0   1      2
27   number_of_seasons_is_zero      0      1   0   1      2
28  number_of_episodes_is_zero      0      1   0   1      2
29    episode_run_time_is_zero      0      1   0   1      2
30                    polarity      1      1   1   1      4
31                subjectivity      1      1   0   1      3
32                   sentiment      0      1   0   1      2
33                   top_words      0      1   1   1      3
34             overview_length      1      1   1   1      4
35               languages_num      0      1   1   1      3
36        spoken_languages_num      0      1   1   1      3
37    production_countries_num      0      1   1   1      3
38                networks_num      0      1   1   1      3
39                  aired_time      1      1   1   1      4
40     avg_episodes_per_season      1      1   1   1      4
41                growth_index      1      1   1   1      4
42                       isCBS      0      1   0   1      2
43                       isFOX      0      1   0   1      2
44                       isNBC      0      1   0   1      2
45                   isNetflix      0      1   0   1      2
46           ismultiple_top_20      0      0   0   0      0
47               is_covid_time      0      1   1   1      3

As it seems the lasso value from the gridsearch exlude a lot of columns, therefor i will change the lasso value until i have a sufficient number of columns to continue to the model

# for the data without the nan fills

In [461]:
lasso = Lasso(alpha=1).fit(x_, y_)
lasso_selected = (np.abs(lasso.coef_) > 0).astype(int)

#Ridge
ridge = Ridge(alpha=5).fit(x_, y_)
ridge_selected = (np.abs(ridge.coef_) > 0).astype(int)

#Gradient Boosting
gb = GradientBoostingRegressor().fit(x_, y_)
gb_selected = (gb.feature_importances_ > 0).astype(int)

#Random Forest
rf = RandomForestRegressor().fit(x_, y_)
rf_selected = (rf.feature_importances_ > 0).astype(int)

# Create a DataFrame with the selected features
selected_features_ = pd.DataFrame({
    'Feature': x_.columns,
    'Lasso': lasso_selected,
    'Ridge': ridge_selected,
    'GB': gb_selected,
    'RF': rf_selected
})

# Sum the totals for each model
selected_features_['Total'] = selected_features[['Lasso','Ridge','GB','RF']].sum(axis=1)
print(selected_features)

                       Feature  Lasso  Ridge  GB  RF  Total
0                           id      1      1   1   1      4
1                         name      1      1   1   1      4
2            number_of_seasons      0      0   0   0      0
3           number_of_episodes      1      1   1   1      4
4            original_language      0      1   1   1      3
5                   vote_count      1      1   1   1      4
6                 vote_average      1      1   1   1      4
7                        adult      0      1   0   1      2
8                in_production      0      1   0   1      2
9                         type      0      1   1   1      3
10                      status      0      1   0   1      2
11                      genres      1      1   1   1      4
12                   languages      0      1   1   1      3
13                    networks      0      1   1   1      3
14              origin_country      1      1   0   1      3
15            spoken_languages      1      1   1   1      4
16        production_countries      1      1   1   1      4
17            episode_run_time      0      1   0   1      2
18                  year_start      0      1   1   1      3
19                 month_start      0      1   0   1      2
20                    year_end      1      1   1   1      4
21                   month_end      0      1   1   1      3
22                changed_name      0      1   1   1      3
23           name_is_duplicate      0      1   1   1      3
24          vote_count_is_zero      0      1   1   1      3
25        vote_average_is_zero      0      1   1   1      3
26   number_of_seasons_is_zero      0      0   0   0      0
27  number_of_episodes_is_zero      1      1   1   1      4
28    episode_run_time_is_zero      0      1   1   1      3
29                    polarity      1      1   1   1      4
30                subjectivity      1      1   1   1      4
31                   sentiment      0      1   1   1      3
32                   top_words      0      1   0   1      2
33             overview_length      1      1   1   1      4
34               languages_num      0      1   1   1      3
35        spoken_languages_num      0      1   1   1      3
36    production_countries_num      0      1   1   1      3
37                networks_num      0      1   1   1      3
38                  aired_time      1      1   1   1      4
39     avg_episodes_per_season      1      1   1   1      4
40                       isCBS      0      1   0   1      2
41                       isFOX      0      1   1   1      3
42                       isNBC      0      1   0   1      2
43                   isNetflix      0      1   1   1      3
44           ismultiple_top_20      0      0   0   0      0
45               is_covid_time      0      1   1   1      3

In [702]:
pd.set_option('display.max_columns', None)
#print(selected_features)
#print(selected_features[selected_features['Total']==4].sum())
print(selected_features[selected_features['Total']==4].value_counts().sum())
#print(selected_features_[selected_features_['Total']==4].value_counts().sum())
# tv_
#print(selected_features_[selected_features_['Total']==4].value_counts().sum())
#print(selected_features[selected_features['Total']==4])

18

# Creating DataFrame with most valuable variables
I am creating 2 df 1 without the NAN imputation to check if the imputation in this case harm the final resulted

In [703]:
final_col_lst = selected_features[selected_features['Total']==4]['Feature'].to_list()
print(final_col_lst)
#final_col_lst_ = selected_features_[selected_features_['Total']==4]['Feature'].to_list()
df_model = tv[final_col_lst].copy()
# not cleaned model 
df_model_ = tv_[final_col_lst].copy()

df_model.info()
# no popularity columns is in the models pikle file - can get than from tv_show.pkl
df_model.to_pickle('tv_model')
df_model_.to_pickle('tv_model_') # the one with no null fills

['id', 'name', 'number_of_seasons', 'number_of_episodes', 'original_language', 'vote_count', 'vote_average', 'type', 'genres', 'spoken_languages', 'production_countries', 'year_start', 'month_end', 'polarity', 'overview_length', 'aired_time', 'avg_episodes_per_season', 'growth_index']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163047 entries, 0 to 163046
Data columns (total 18 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       163047 non-null  int64
 1   name                     163047 non-null  int64
 2   number_of_seasons        163047 non-null  int64
 3   number_of_episodes       163047 non-null  int64
 4   original_language        163047 non-null  int64
 5   vote_count               163047 non-null  int64
 6   vote_average             163047 non-null  float64
 7   type                     163047 non-null  int64
 8   genres                   163047 non-null  int64
 9   spoken_languages         163047 non-null  int64
 10  production_countries     163047 non-null  int64
 11  year_start               163047 non-null  float64
 12  month_end                163047 non-null  float64
 13  polarity                 163047 non-null  int64
 14  overview_length          163047 non-null  int64
 15  aired_time               163047 non-null  float64
 16  avg_episodes_per_season  163047 non-null  float64
 17  growth_index             163047 non-null  float64
dtypes: float64(6), int64(12)
memory usage: 22.4 MB